### ISSUE TITLE
ember generate component fails

### ISSUE THREAD

**Issue by buschtoens** [Vestorly/ember-cli-emblem#20]
When `ember-cli-emblem` is installed, component generation via `ember generate my-component` fails.

Originally reported here: https://github.com/ember-cli/ember-cli/issues/4099#issuecomment-106653620

Disabling the blueprints fixes the bug:

```
ENV.emblemOptions = {
  blueprints: false
};
```

**Comment by buschtoens** [comment]
```
jan@ubuntu:~/code/citb$ ember g component news-shwowcase
version: 0.2.5-master-6eec996343
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
installing
Arguments to path.join must be strings
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:467:13)
    at __path__ (/home/jan/code/ember-cli/blueprints/component/index.js:26:23)
    at /home/jan/code/ember-cli/lib/models/blueprint.js:629:66
    at Array.map (native)
    at Class.Blueprint.generateFileMap (/home/jan/code/ember-cli/lib/models/blueprint.js:629:37)
    at Class.Blueprint._locals (/home/jan/code/ember-cli/lib/models/blueprint.js:815:22)
    at Class.Blueprint._process (/home/jan/code/ember-cli/lib/models/blueprint.js:459:22)
    at Class.Blueprint.install (/home/jan/code/ember-cli/lib/models/blueprint.js:492:15)
    at Class.module.exports.Task.extend.run (/home/jan/code/ember-cli/lib/tasks/generate-from-blueprint.js:52:49)
    at Class.module.exports.Command.extend.run (/home/jan/code/ember-cli/lib/commands/generate.js:76:17)
jan@ubuntu:~/code/citb$ ember version
version: 0.2.5-master-6eec996343
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
node: 2.1.0
npm: 2.11.0
```

**Comment by trabus** [comment]
It seems that ember-cli-emblem is using the built-in component blueprint in a way that I wasn't aware that addon developers were using it. They're looking up the built-in blueprint and passing through their own options:
```
locals: function(options) {
    return this.lookupBlueprint('component').locals(options);
  },
```
Because their options object doesn't contain `path`, it blows up. I just need to add a default value for cases like this.

This should be a simple fix, and thank you for pointing this out!

**Comment by buschtoens** [comment]
Awesome! Thanks a lot for your constant and very swift work. 💎

I'll leave this issue open until the fix landed in master.

**Comment by joebartels** [comment]
:+1:
