### ISSUE TITLE
TypeError: Cannot read property 'writeLine' of undefined

### ISSUE THREAD

**Issue by buschtoens** [Vestorly/ember-cli-emblem#25]
```
jan@ubuntu:~/code/citb/citb-website$ ember v
version: 1.13.1
node: 2.3.0
npm: 2.12.1
jan@ubuntu:~/code/citb/citb-website$ ember g route blog
version: 1.13.1
installing route
  create app/blog/route.js
  create app/blog/template.emblem
Cannot read property 'writeLine' of undefined
TypeError: Cannot read property 'writeLine' of undefined
    at Class.module.exports.afterInstall (/home/jan/code/citb/citb-website/node_modules/ember-cli/blueprints/route/index.js:68:14)
    at Class.module.exports.afterInstall (/home/jan/code/citb/citb-website/node_modules/ember-cli-emblem/blueprints/route/index.js:35:42)
    at Class.module.exports.afterInstall (/home/jan/code/citb/citb-website/node_modules/ember-cli-emblem/blueprints/route/index.js:35:42)
    at lib$rsvp$$internal$$tryCatch (/home/jan/code/citb/citb-website/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/home/jan/code/citb/citb-website/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/home/jan/code/citb/citb-website/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/home/jan/code/citb/citb-website/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
```

`ember g route` and `ember d route` both fail with this error.

**Comment by buschtoens** [comment]
For some reason, [`this.ui`](https://github.com/ember-cli/ember-cli/blob/v1.13.1/blueprints/route/index.js#L68) is undefined. It works, when I uninstall `ember-cli-emblem`.

**Comment by buschtoens** [comment]
Possibly related: https://github.com/ember-cli/ember-cli/issues/2255
