### ISSUE TITLE
Route blueprint not working in Ember 2.13

### ISSUE THREAD

**Issue by tmeloliveira** [Vestorly/ember-cli-emblem#55]
The route blueprint is no longer working on Ember **2.13** and ember-cli-emblem **0.9.0**

This is the error I get when I try to run `ember g route test`:

```
Cannot read property 'moduleName' of undefined
TypeError: Cannot read property 'moduleName' of undefined
    at __name__ ( ... /node_modules/ember-source/blueprints/route/index.js:35:30)
    at fileMapValues.map.token ( ... /node_modules/ember-cli/lib/models/blueprint.js:633:50)
    at Array.map (native)
    at Class.generateFileMap ( ... /node_modules/ember-cli/lib/models/blueprint.js:633:37)
    at Promise.then.customLocals ( ... /node_modules/ember-cli/lib/models/blueprint.js:827:26)
    at tryCatch ( ... /node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback ( ... /node_modules/rsvp/dist/rsvp.js:554:13)
    at  ... /node_modules/rsvp/dist/rsvp.js:629:16
    at flush ( ... /node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

PS.: I have omitted my project's path and replaced with `...`

**Comment by dhilipsiva** [comment]
For anyone facing the same Issue: I had the same error. As a temporary workaround, I just delete `ember-cli-emblem` entry in my `package.json`, generate route and add the package again. Works for me for the time being.

cc: @tmeloliveira @renatocarvalho @discandanty

**Comment by Dylan0203** [comment]
same here with ember 2.14
thanks @dhilipsiva for the workaround
```
 ~/Projects/testing   master  ember g route about
installing route
Cannot read property 'moduleName' of undefined
TypeError: Cannot read property 'moduleName' of undefined
    at __name__ (/.../node_modules/ember-source/blueprints/route/index.js:35:30)
    at fileMapValues.map.token (/.../node_modules/ember-cli/lib/models/blueprint.js:634:50)
    at Array.map (native)
    at Class.generateFileMap (/.../node_modules/ember-cli/lib/models/blueprint.js:634:37)
    at Promise.then.customLocals (/.../node_modules/ember-cli/lib/models/blueprint.js:828:26)
    at tryCatch (/.../node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/.../node_modules/rsvp/dist/rsvp.js:538:13)
    at /.../node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/.../node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

**Comment by vburzynski** [comment]
I just started a new project and installed this using ember-cli 2.18.1, seems to work now. Perhaps something has changed since Ember 2.13 and 2.14?

Also, is this project dead?

**Comment by Gaurav0** [comment]
Hi, @vburzynski. I work for Vestorly. While we are certainly happy to continue to accept PRs for this project, we are migrating away from using Emblem in our codebase and thus are not likely to continue to maintain it over the long term. We don't know if Emblem compiler will be continued to be supported through upcoming changes to hbs in Ember 3.0 either, given that its maintainer is no longer actively using it. I won't say it's dead, but I would be hesitant to recommend it for new projects.

**Comment by thec0keman** [comment]
Our organization makes heavy use of Emblem and I plan to continue helping maintain Emblem for the foreseeable future.  I'd be happy to help out with this project as well.

**Comment by renatocarvalho** [comment]
@Gaurav0 I would suggest you guys look for a new maintainer.

**Comment by christophercurrie** [comment]
I made a fork a while back that fixes some issues in later Ember versions, it may have resolved this one as well: https://github.com/fizmo/ember-cli-emblem
